# .github/workflows/sync.yml
name: Sync Knowledge Base to Qdrant

on:
  push:
    branches:
      - main
    paths:
      - 'it/**'
      - 'marketing/**'
      - 'projekty/**'
      - '.knowledge_manifest.yml'
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 1. Checkout Knowledge Base repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Sparse checkout sync script from Bot repository
        run: |
          mkdir skryba-bot-code
          cd skryba-bot-code
          git init
          git remote add origin https://github.com/Wiecek-K/discord-skryba-bot.git
          git config core.sparseCheckout true
          echo "bot/scripts/" >> .git/info/sparse-checkout
          echo "requirements.txt" >> .git/info/sparse-checkout
          git pull --depth=1 origin main
        
      - name: 4. Install Python dependencies from bot repo
        run: pip install -r skryba-bot-code/requirements.txt

      # --- NOWY KROK DIAGNOSTYCZNY ---
      - name: 5. Display connection details
        run: echo "Attempting to connect to Qdrant at URL: http://${{ secrets.QDRANT_HOST_IP }}:6333"

      # Krok uruchamiający skrypt jest teraz krokiem nr 6
      - name: 6. Run the sync script from bot repo
        run: python skryba-bot-code/bot/scripts/sync_to_qdrant.py
        env:
          QDRANT_HOST: ${{ secrets.QDRANT_HOST_IP }}
          QDRANT_PORT: 6333
